name: Go CI

on:
  workflow_call:
    inputs:
      working_directory:
        default: ${{ github.workspace }}
        type: string
        description: Working directory for go code

jobs:
  go:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Debug
        run: "echo 'Working directory: ${{ inputs.working_directory }}' && pwd"
        working-directory: ${{ inputs.working_directory }}

      - run: go mod download
        working-directory: ${{ inputs.working_directory }}

      - name: Format check
        run: go fmt ./...
        working-directory: ${{ inputs.working_directory }}

      - name: Lint
        run: go vet ./...
        working-directory: ${{ inputs.working_directory }}

      - name: Test
        run: go test -cover ./...
        working-directory: ${{ inputs.working_directory }}
