name: Version

on:
  workflow_dispatch:
  workflow_call:

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ vars.PLATFORM_GH_APP_CLIENT_ID }}
          private-key: ${{ secrets.PLATFORM_GH_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Version Bump
        run: cog bump --auto

      - name: Check if bumped
        id: check
        run: |
          if [ "$(git rev-parse HEAD)" != "${{ github.sha }}" ]; then
            echo "bumped=true" >> "${GITHUB_OUTPUT}"
          else
            echo "bumped=false" >> "${GITHUB_OUTPUT}"
          fi

      - name: Push bump commit
        if: steps.check.outputs.bumped == 'true'
        run: git push

      - name: Push release tag
        if: steps.check.outputs.bumped == 'true'
        run: git push origin $(git describe --tags --abbrev=0)
